[package]
name = "pvz-pak-tool"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "pkt"
path = "src/main.rs"

[dependencies]
clap = { version = "4.0", features = ["derive", "color"] }
encoding_rs = "0.8"
colored = "2.0"
